# Generated by Django 2.0.7 on 2019-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('email', models.CharField(default='None', max_length=200)),
                ('subject', models.CharField(default='None', max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
