# Generated by Django 2.0.7 on 2019-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='image_url',
            field=models.CharField(default='image_2.jpg', max_length=200),
        ),
    ]
