# Generated by Django 2.0.7 on 2019-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=255)),
                ('predict', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('image_url', models.CharField(default='image_2.jpg', max_length=200)),
                ('star', models.IntegerField(default=5)),
                ('about_more_url', models.CharField(default='http://www.baidu.com', max_length=200)),
                ('type', models.CharField(max_length=40)),
                ('port', models.IntegerField(default=9000)),
                ('address', models.CharField(max_length=100)),
                ('input_tensor_name', models.CharField(default='images', max_length=100)),
                ('model_name', models.CharField(default='inception', max_length=100)),
                ('signature_name', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
