# Generated by Django 2.0.7 on 2019-04-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpost',
            old_name='describ',
            new_name='describe',
        ),
    ]
