# Generated by Django 2.0.7 on 2019-04-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190416_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='input_tensor_name',
            field=models.CharField(default='images', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='model_name',
            field=models.CharField(default='inception', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='signature_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
