# Generated by Django 2.0.7 on 2019-03-05 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('config', models.TextField()),
                ('download', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('precolor', models.TextField(default='')),
            ],
            options={
                'ordering': ('-like', '-created'),
            },
        ),
        migrations.CreateModel(
            name='CoursesHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.CharField(max_length=25)),
                ('contact', models.CharField(default='选填', max_length=25)),
                ('type', models.CharField(default='Adaptation', max_length=10)),
                ('url', models.CharField(default='#', max_length=100)),
                ('html', models.TextField()),
                ('valid', models.BooleanField(default=True)),
                ('adapted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('eas', models.CharField(default='Unknown', max_length=25)),
            ],
            options={
                'ordering': ('read', 'adapted', '-type', '-valid', 'created'),
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=25)),
                ('money', models.CharField(max_length=10)),
                ('label', models.CharField(default='None', max_length=25)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
